services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cdss_db
      - MYSQL_USER=cdss_user
      - MYSQL_PASSWORD=cdss_pass
    ports:
      - "9306:3306"

  app:
    build: .
    container_name: cdss-api-app
    ports:
      - "9080:8080"
    depends_on:
      - mysqldb
    environment:
      - primary.datasource.url=jdbc:mysql://mysqldb:3306/cdss_db
      - primary.datasource.username=cdss_user
      - primary.datasource.password=cdss_pass

