name: Build and Deploy

on:
  push:
    branches: [ staging ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry-1.docker.io

      - name: Debug
        run: |
          cat ~/.docker/config.json
          docker info | grep -i username
          docker pull hello-world
          echo "Image name: ${{ secrets.DOCKER_USER }}/cdss-api:${{ github.sha }}"

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/cdss-api:${{ github.sha }} .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/cdss-api:${{ github.sha }}

  deploy-to-k8s:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Update K8s Deployment
        run: |
          kubectl set image deployment/cdss-api-app \
            cdss-api=${{ secrets.DOCKER_USER }}/cdss-api:${{ github.sha }} \
            --record

      - name: Verify Rollout
        run: kubectl rollout status deployment/cdss-api-app --timeout=120s

      - name: Rollback on Failure
        if: failure()
        run: kubectl rollout undo deployment/cdss-api-app